// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKZwwL8I7BW5Kl-f5fpJEJRPyt78SKch8',
    appId: '1:762702355526:web:78176f2177fabbb8c4be47',
    messagingSenderId: '762702355526',
    projectId: 'winampro',
    authDomain: 'winampro.firebaseapp.com',
    databaseURL: 'https://winampro-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'winampro.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgy43O9BwgfEbYxkJDX7l8mBTW6VLt95s',
    appId: '1:762702355526:android:32cc4b9bc29ea140c4be47',
    messagingSenderId: '762702355526',
    projectId: 'winampro',
    databaseURL: 'https://winampro-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'winampro.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMBWm4m05IOvrdwmrXp94aVHGSJnbcduw',
    appId: '1:762702355526:ios:86c6ca8df8a6bc03c4be47',
    messagingSenderId: '762702355526',
    projectId: 'winampro',
    databaseURL: 'https://winampro-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'winampro.firebasestorage.app',
    iosBundleId: 'com.example.winampPro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMBWm4m05IOvrdwmrXp94aVHGSJnbcduw',
    appId: '1:762702355526:ios:86c6ca8df8a6bc03c4be47',
    messagingSenderId: '762702355526',
    projectId: 'winampro',
    databaseURL: 'https://winampro-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'winampro.firebasestorage.app',
    iosBundleId: 'com.example.winampPro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKZwwL8I7BW5Kl-f5fpJEJRPyt78SKch8',
    appId: '1:762702355526:web:fda8117e2a0943d7c4be47',
    messagingSenderId: '762702355526',
    projectId: 'winampro',
    authDomain: 'winampro.firebaseapp.com',
    databaseURL: 'https://winampro-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'winampro.firebasestorage.app',
  );
}
